In [33]:
# 데이터 내용 미리보기
import pandas as pd
pd.set_option('display.width', 200)
pd.set_option('display.max_columns', None)


df = pd.read_csv('./data/auto-mpg.csv',header=None)

df.columns = ['mpg','cylinders','dosplacement','horesepower','weight',
			  'accerleration','model year', 'origin','name']

df.head()

    mpg  cylinders  dosplacement horesepower  weight  accerleration  model year  origin                       name
0  18.0          8         307.0       130.0  3504.0           12.0          70       1  chevrolet chevelle malibu
1  15.0          8         350.0       165.0  3693.0           11.5          70       1          buick skylark 320
2  18.0          8         318.0       150.0  3436.0           11.0          70       1         plymouth satellite
3  16.0          8         304.0       150.0  3433.0           12.0          70       1              amc rebel sst
4  17.0          8         302.0       140.0  3449.0           10.5          70       1                ford torino

In [34]:
# 데이터 요약 정보 확인하기

df.shape

(398, 9)

In [35]:
## 각 열의 자료형을 알 수 있다
df.dtypes

mpg              float64
cylinders          int64
dosplacement     float64
horesepower          str
weight           float64
accerleration    float64
model year         int64
origin             int64
name                 str
dtype: object

In [36]:
## 데이터 프레임의 기술 통계 정보 요약
df.describe()

              mpg   cylinders  dosplacement       weight  accerleration  model year      origin
count  398.000000  398.000000    398.000000   398.000000     398.000000  398.000000  398.000000
mean    23.514573    5.454774    193.425879  2970.424623      15.568090   76.010050    1.572864
std      7.815984    1.701004    104.269838   846.841774       2.757689    3.697627    0.802055
min      9.000000    3.000000     68.000000  1613.000000       8.000000   70.000000    1.000000
25%     17.500000    4.000000    104.250000  2223.750000      13.825000   73.000000    1.000000
50%     23.000000    4.000000    148.500000  2803.500000      15.500000   76.000000    1.000000
75%     29.000000    8.000000    262.000000  3608.000000      17.175000   79.000000    2.000000
max     46.600000    8.000000    455.000000  5140.000000      24.800000   82.000000    3.000000

In [37]:
df.describe(include='all')

               mpg   cylinders  dosplacement horesepower       weight  accerleration  model year      origin        name
count   398.000000  398.000000    398.000000         398   398.000000     398.000000  398.000000  398.000000         398
unique         NaN         NaN           NaN          94          NaN            NaN         NaN         NaN         305
top            NaN         NaN           NaN       150.0          NaN            NaN         NaN         NaN  ford pinto
freq           NaN         NaN           NaN          22          NaN            NaN         NaN         NaN           6
mean     23.514573    5.454774    193.425879         NaN  2970.424623      15.568090   76.010050    1.572864         NaN
std       7.815984    1.701004    104.269838         NaN   846.841774       2.757689    3.697627    0.802055         NaN
min       9.000000    3.000000     68.000000         NaN  1613.000000       8.000000   70.000000    1.000000         NaN
25%      17.500000    4.000000    104.250000         NaN  2223.750000      13.825000   73.000000    1.000000         NaN
50%      23.000000    4.000000    148.500000         NaN  2803.500000      15.500000   76.000000    1.000000         NaN
75%      29.000000    8.000000    262.000000         NaN  3608.000000      17.175000   79.000000    2.000000         NaN
max      46.600000    8.000000    455.000000         NaN  5140.000000      24.800000   82.000000    3.000000         NaN

In [38]:
df.describe(include='number')

              mpg   cylinders  dosplacement       weight  accerleration  model year      origin
count  398.000000  398.000000    398.000000   398.000000     398.000000  398.000000  398.000000
mean    23.514573    5.454774    193.425879  2970.424623      15.568090   76.010050    1.572864
std      7.815984    1.701004    104.269838   846.841774       2.757689    3.697627    0.802055
min      9.000000    3.000000     68.000000  1613.000000       8.000000   70.000000    1.000000
25%     17.500000    4.000000    104.250000  2223.750000      13.825000   73.000000    1.000000
50%     23.000000    4.000000    148.500000  2803.500000      15.500000   76.000000    1.000000
75%     29.000000    8.000000    262.000000  3608.000000      17.175000   79.000000    2.000000
max     46.600000    8.000000    455.000000  5140.000000      24.800000   82.000000    3.000000

In [39]:
df.describe(include='object')

C:\Users\Win11Pro\AppData\Local\Temp\ipykernel_17988\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       horesepower        name
count          398         398
unique          94         305
top          150.0  ford pinto
freq            22           6

In [40]:
# 데이터 개수 확인
print(df.count())
print(type(df.count()))

mpg              398
cylinders        398
dosplacement     398
horesepower      398
weight           398
accerleration    398
model year       398
origin           398
name             398
dtype: int64
<class 'pandas.Series'>

In [41]:
# 각 열의 고유값 개수
## 객체["해당열"].value_count()
unique_values = df['origin'].value_counts()
unique_values

origin
1    249
3     79
2     70
Name: count, dtype: int64

In [42]:
## 고유값의 상대적 비율
unique_values_ratio = df['origin'].value_counts(normalize=True)
unique_values_ratio

origin
1    0.625628
3    0.198492
2    0.175879
Name: proportion, dtype: float64

In [43]:
unique_values_percentage = (df['origin'].value_counts(normalize=True)*100).round(1)
unique_values_percentage

origin
1    62.6
3    19.8
2    17.6
Name: proportion, dtype: float64

In [44]:
# 평균값
import pandas as pd

df = pd.read_csv('./data/auto-mpg.csv',header=None)

df.columns = ['mpg','cylinders','dosplacement','horesepower','weight',
			  'accerleration','model year', 'origin','name']
# print(df)
# print()
print(df.mean(numeric_only=True))
print()
print(df['mpg'].mean())
print(df.mpg.mean())
print()
print(df[['mpg','weight']].mean())

mpg                23.514573
cylinders           5.454774
dosplacement      193.425879
weight           2970.424623
accerleration      15.568090
model year         76.010050
origin              1.572864
dtype: float64

23.514572864321607
23.514572864321607

mpg         23.514573
weight    2970.424623
dtype: float64

In [45]:
# 중앙값
print(df.median(numeric_only=True))
print()
print(df['mpg'].median())

mpg                23.0
cylinders           4.0
dosplacement      148.5
weight           2803.5
accerleration      15.5
model year         76.0
origin              1.0
dtype: float64

23.0

In [46]:
# 최댓값
print(df.max(numeric_only=True))
print()
print(df['mpg'].max())

mpg                46.6
cylinders           8.0
dosplacement      455.0
weight           5140.0
accerleration      24.8
model year         82.0
origin              3.0
dtype: float64

46.6

In [47]:
# 최솟값
print(df.min(numeric_only=True))
print()
print(df['mpg'].min())

mpg                 9.0
cylinders           3.0
dosplacement       68.0
weight           1613.0
accerleration       8.0
model year         70.0
origin              1.0
dtype: float64

9.0

In [48]:
# 표준편차
print(df.std(numeric_only=True))
print()
print(df['mpg'].std())

mpg                7.815984
cylinders          1.701004
dosplacement     104.269838
weight           846.841774
accerleration      2.757689
model year         3.697627
origin             0.802055
dtype: float64

7.815984312565782

In [49]:
# 상관계수
print(df.corr(numeric_only=True))
print()
print(df[['mpg','weight']].corr())

                    mpg  cylinders  dosplacement    weight  accerleration  model year    origin
mpg            1.000000  -0.775396     -0.804203 -0.831741       0.420289    0.579267  0.563450
cylinders     -0.775396   1.000000      0.950721  0.896017      -0.505419   -0.348746 -0.562543
dosplacement  -0.804203   0.950721      1.000000  0.932824      -0.543684   -0.370164 -0.609409
weight        -0.831741   0.896017      0.932824  1.000000      -0.417457   -0.306564 -0.581024
accerleration  0.420289  -0.505419     -0.543684 -0.417457       1.000000    0.288137  0.205873
model year     0.579267  -0.348746     -0.370164 -0.306564       0.288137    1.000000  0.180662
origin         0.563450  -0.562543     -0.609409 -0.581024       0.205873    0.180662  1.000000

             mpg    weight
mpg     1.000000 -0.831741
weight -0.831741  1.000000