In [ ]:
# index 활용

import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [3]:
print(df.ndim)
print(df.shape)

2
(3, 5)

In [4]:
# Grouping 에 사용
ndf = df.set_index(['이름'])
ndf2 = ndf.set_index('음악')
ndf3 = ndf.set_index(['수학','음악'])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [5]:
# 행 인덱스 재배열
dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,11,12],
	"c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index = ['r0','r1','r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [6]:
new_index = ['r0', 'r1','r2','r3','r4']
ndf = df.reindex(new_index)
print(ndf)

ndf2 = df.reindex(new_index,fill_value=0)
print(ndf2)

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [ ]:
# 행 인덱스 초기화

import pandas as pd

dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,11,12],
	"c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index = ['r0', 'r1', 'r2'])
print(df)
print()

ndf = df.reset_index()
print(ndf)
print()

ndf2 = df.reset_index(names=['C00'])
print(ndf2)
print()

#***
ndf3 = df.reset_index(drop=True)
print(ndf3)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

  C00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [17]:
# 행 인덱스를 기준으로 데이터프레임 정렬

import pandas as pd

dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,11,12],
	"c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index = ['r0', 'r1', 'r2'])

ndf = df.sort_index(ascending=False)
print(ndf)
print()
# print()
# print()


ndf2 = df.sort_index(ascending=True)
ndf2

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [ ]:
# 열 기준 정렬

import pandas as pd

dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,10,11],
	"c4" : [15,14,14]
}

df = pd.DataFrame(dict_data, index = ['r0', 'r1', 'r2'])

ndf = df.sort_values(by='c1', ascending= False)
print(ndf)
print()

ndf2 = df.sort_values(by='c2', ascending=True)
print(ndf2)
print()

# 중복된 숫자일 경우 먼저 나온 것을 기준으로 하고 정렬함
ndf3 = df.sort_values(by=['c3','c4'], ascending=[False, True])
ndf3

    c0  c1  c2  c3  c4
r2   3   6   9  11  14
r1   2   5   8  10  14
r0   1   4   7  10  15

    c0  c1  c2  c3  c4
r0   1   4   7  10  15
r1   2   5   8  10  14
r2   3   6   9  11  14

    c0  c1  c2  c3  c4
r2   3   6   9  11  14
r1   2   5   8  10  14
r0   1   4   7  10  15