In [3]:
# 산술연산
# Serise객체 + 연산자(+,-,*,/) + 숫자
import pandas as pd

student1 = pd.Series({'국어' : 100,
					  '영어' : 80,
					  '수학' : 90})
# print(student1)


percentage = student1/200

print(percentage)
print(type(percentage))

국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [4]:
#시리즈 vs. 시리즈
# Series1 + 연산자(+,-,*,/) + Series2
import pandas as pd

student1 = pd.Series({'국어' : 100,
					  '영어' : 80,
					  '수학' : 90})
student2 = pd.Series({'국어' : 80,
					  '영어' : 90,
					  '수학' : 80})

addition = student1 + student2
print(addition)
print(type(addition))
print()

subtraction = student1 - student2
print(subtraction)
print(type(subtraction))
print()

mul = student1 * student2
print(mul)
print(type(mul))
print()

div = student1 / student2
print(type(div))
print(div)

result = pd.DataFrame([addition, subtraction, mul,div], index=['덧셈', '뺄셈', '곱셈','나눗셈'])
result

국어    180
영어    170
수학    170
dtype: int64
<class 'pandas.Series'>

국어    20
영어   -10
수학    10
dtype: int64
<class 'pandas.Series'>

국어    8000
영어    7200
수학    7200
dtype: int64
<class 'pandas.Series'>

<class 'pandas.Series'>
국어    1.250000
영어    0.888889
수학    1.125000
dtype: float64

          국어           영어        수학
덧셈    180.00   170.000000   170.000
뺄셈     20.00   -10.000000    10.000
곱셈   8000.00  7200.000000  7200.000
나눗셈     1.25     0.888889     1.125

In [5]:
# NaN 값이 있는 시리즈 연산
import pandas as pd
import numpy as np

student1 = pd.Series({'국어' : np.nan,
					  '영어' : 80,
					  '수학' : 90})
student2 = pd.Series({'수학' : 80,
					  '국어' : 90})

add = student1 + student2
sub = student1 - student2
mul = student2 * student1
div = student1 / student2

print(type(div))
print()

result = pd.DataFrame([add, sub, mul,div], index=['덧셈', '뺄셈', '곱셈','나눗셈'])
result

<class 'pandas.Series'>

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [6]:
# 연산 메소드
import pandas as pd
import numpy as np

student1 = pd.Series({'국어' : np.nan,
					  '영어' : 80,
					  '수학' : 90})
student2 = pd.Series({'수학' : 80,
					  '국어' : 90})

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd.DataFrame([sr_add,sr_sub,sr_mul,sr_div], index=['덧셈', '뺄셈', '곱셈','나눗셈'])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [7]:
# 데이터프레임 연산

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
# 앞에서 5개만 출력
print(df.head())
print(type(df))
print()

add = df + 10
print(add.head())
print(type(add))
print()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
<class 'pandas.DataFrame'>

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500
<class 'pandas.DataFrame'>

In [8]:
# 데이터프레임끼리 더하기

import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

add = df + 10

sub = add - df
# 끝에서 5개만 출력
print(sub.tail())
print(type(sub))

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0
<class 'pandas.DataFrame'>

In [18]:
sample1 = add.tail(10).fillna(0.0)
sample1.shape
sample1

      age  fare
881  10.0  10.0
882  10.0  10.0
883  10.0  10.0
884  10.0  10.0
885  10.0  10.0
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [19]:
sample2 = sub.tail(10).fillna(0)
sample2.shape
sample2

      age  fare
881  10.0  10.0
882  10.0  10.0
883  10.0  10.0
884  10.0  10.0
885  10.0  10.0
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [24]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)

print(df_add)
print()
print(df_sub)
print()
print(df_mul)
print()
print(df_div)

      age     fare
881  53.0  27.8958
882  42.0  30.5167
883  48.0  30.5000
884  45.0  27.0500
885  59.0  49.1250
886  47.0  33.0000
887  39.0  50.0000
888   0.0  43.4500
889  46.0  50.0000
890  52.0  27.7500

      age     fare
881  33.0   7.8958
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
888   0.0  23.4500
889  26.0  30.0000
890  32.0   7.7500

       age     fare
881  430.0  178.958
882  320.0  205.167
883  380.0  205.000
884  350.0  170.500
885  490.0  391.250
886  370.0  230.000
887  290.0  400.000
888    0.0  334.500
889  360.0  400.000
890  420.0  177.500

     age     fare
881  4.3  1.78958
882  3.2  2.05167
883  3.8  2.05000
884  3.5  1.70500
885  4.9  3.91250
886  3.7  2.30000
887  2.9  4.00000
888  NaN  3.34500
889  3.6  4.00000
890  4.2  1.77500