In [136]:
# 시리즈
## 외부라이브러리 pandas설치

##라이브러리 불러오기
import pandas as pd

dict_data = {
	'a' : 1,
	'b' : 2,
	'c' : 3
}

sr = pd.Series(dict_data)
print(type(sr))
print(sr)

<class 'pandas.Series'>
a    1
b    2
c    3
dtype: int64

In [137]:
## 인덱스
## series객체.index
print(sr.index)

Index(['a', 'b', 'c'], dtype='str')

In [138]:
## 데이터 값 배열
## Series객체.values

print(sr.values)

[1 2 3]

In [139]:
## 시리즈 인덱스
import pandas as pd
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr)

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [140]:
## 인덱스
print(sr.index)

## values
val = sr.values
print(val)

## 시리즈 객체의 데이터 타입 확인
print(sr.dtype)

## 시리즈 객체의 원소 개수 확인
print(len(sr))

## 시리즈 배열의 형태 확인 / shape 속성
print(sr.shape)

## 데이터 구조의 차원 수
print(sr.ndim)

RangeIndex(start=0, stop=5, step=1)
['2019-01-02' 3.14 'ABC' 100 True]
object
5
(5,)
1

In [141]:
# 원소선택
import pandas as pd

tup_data = ('영인', '2010-05-01','여',True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)



print(sr.iloc[0])
# print(sr[0])   #인덱스가 문자열인 경우만 가능.
print()
print(sr['이름'])


# print(sr[1,2])
print('\n')
print(sr[['생년월일', '성별']])

print(pd.Series(5))
print()
print(pd.Series(5, index = ['a','b','c']))

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
영인

영인


생년월일    2010-05-01
성별               여
dtype: object
0    5
dtype: int64

a    5
b    5
c    5
dtype: int64

In [142]:
#데이터프레임
## 딕셔너리 -> 데이터 프레임으로 변환
## pandas.DataFrame(딕셔너리)

import pandas as pd

dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,11,12],
	"c4" : [13,14,15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)
df

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [143]:
# 행 인덱스 / 열 이름 설정
import pandas as pd
df = pd.DataFrame([[15,'남','덕영중'],[17,'여','수리중']],
				   index = ['준서','예은'],
				   columns=['나이','성별','학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [144]:
##인덱스 / 칼럼 명 가져오기
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [145]:
#인덱스 / 칼럼 명 변경
df.index = ['학생1','학생2']
df.columns = ['연령','남녀','소속']
print(df)
print()
print(df.index)
print()
print(df.columns)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

Index(['학생1', '학생2'], dtype='str')

Index(['연령', '남녀', '소속'], dtype='str')

In [146]:
# rename을 사용하여 인덱스/칼럼 명 변경    **재할당하지않으면 안바뀜
import pandas as pd
df = pd.DataFrame([[15,'남','덕영중'],[17,'여','수리중']],
				   index = ['준서','예은'],
				   columns=['나이','성별','학교'])

df = df.rename(columns={'나이' : '연령', '성별' : '남녀', '학교':'소속'})
print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [147]:
# 행/열 삭제
## 행 삭제

import pandas as pd

exam_data = {'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
print(df)

df2 = df.copy()
df2 = df2.drop('우현')         # 지우고 재할당 꼭 해야함
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [148]:
#axis는 행을 삭제할 것인지 열을 삭제할 것인지 선택

df3 = df.copy()
df3 = df3.drop(['우현', '인아'], axis=0)
print(df3)
print()

df4 = df.copy()
df4 = df4.drop(['우현', '인아'], axis='index')
print(df4)
print()

df5 = df.copy()
df5 = df5.drop(index = ['우현'])
print(df5)

    수학  영어  음악   체육
서준  90  98  85  100

    수학  영어  음악   체육
서준  90  98  85  100

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [149]:
## 열 삭제
import pandas as pd

exam_data = {'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data, index = ['서준', '우현', '인아'])

df2 = df.copy()
df2 = df2.drop('수학', axis=1)
print(df2)
print()

df3 = df.copy()
df3 = df3.drop(['영어', '음악'],axis =1)
print(df3)
print()

df4 = df.copy()
df4 = df4.drop(['영어', '음악'],axis = 'columns')
print(df4)
print()

df5 = df.copy()
df5 = df5.drop(columns=['수학'])
print(df5)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

    수학   체육
서준  90  100
우현  80   90
인아  70   90

    수학   체육
서준  90  100
우현  80   90
인아  70   90

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [150]:
# 행 선택
import pandas as pd

exam_data = {'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])

labell = df.loc['서준']
position = df.iloc[1]
print(labell)
print()
print(position)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학    80
영어    89
음악    95
체육    90
Name: 우현, dtype: int64

In [151]:
label2 = df.loc[['서준','우현']]
print(label2)
print()

position2 = df.iloc[[0,1]]
print(position2)
print()

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [152]:
#열 선택
import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data)
print(type(df))
df

<class 'pandas.DataFrame'>

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [153]:
math1 = df['수학']
print(math1)
print()
print(type(math1))

math2 = df[['수학']]
print(math2)

0    90
1    80
2    70
Name: 수학, dtype: int64

<class 'pandas.Series'>
   수학
0  90
1  80
2  70

In [154]:
music_gym = df[['음악','체육']]
print(music_gym)
print()
print(df.iloc[ : : 2])
print()

#원소 선택
df = df.set_index('이름')
print(df)

    음악   체육
0   85  100
1   95   90
2  100   90

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [155]:
import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [156]:
## 인덱스 이름: df객체.loc[행인덱스, 열이름]
## 정수 위치 인덱스 : df객체.iloc[행번호, 열번호]

print(df.loc["서준",'음악'])
print(df.iloc[0,2])

KeyError: '서준'

In [ ]:
# 열추가
# df객체["추가하려는 열 이름"] = 데이터값
import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data)
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [ ]:
df["미술"] = [80,90,100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [158]:
# 행 추가
# df 객체.loc["새로운 행 이름"] = 데이터 값 또는 배열
df.loc[2]
df.loc[3] = 0
df.loc[4] = ['동규', 90,80,70,60]
df.loc[5] = df.loc[3]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60
5   0   0   0    0    0

In [ ]:
##원소 값 변경
import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}

df = pd.DataFrame(exam_data)

df = df.set_index('이름')

df.iloc[0,3] = 80
# df.loc['서준']['체육'] = 90        ---->적용안됨/ 대괄호연속사용x 
df.loc['서준','체육'] = 100
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [197]:
# 행, 열의 위치 바꾸기

import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}
df = pd.DataFrame(exam_data)

df = df.transpose()
print(df)
print()

df = df.T
print(df)

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90