In [12]:
#

import pandas as pd

exam_data = {'이름' : ['서준','우현','인아'],
			'수학' :[90,80,70], '영어':[98, 89, 95],
			 '음악' :[85,95,100], '체육' :[100,90,90]}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [2]:
print(df.ndim)
print(df.shape)

2
(3, 5)

In [ ]:
# Grouping 에 사용
ndf = df.set_index(['이름'])
ndf2 = ndf.set_index('음악')
ndf3 = ndf.set_index(['수학','음악'])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [11]:
# 행 인덱스 재배열
dict_data = {
	"c0" : [1,2,3],
	"c1" : [4,5,6],
	"c2" : [7,8,9],
	"c3" : [10,11,12],
	"c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index = ['r0','r1','r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [14]:
new_index = ['r0', 'r1','r2','r3','r4']
ndf = df.reindex(new_index)
print(ndf)

ndf2 = df.reindex(new_index,fill_value=0)
print(ndf2)

     이름  수학  영어  음악  체육
r0  NaN NaN NaN NaN NaN
r1  NaN NaN NaN NaN NaN
r2  NaN NaN NaN NaN NaN
r3  NaN NaN NaN NaN NaN
r4  NaN NaN NaN NaN NaN

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.